### ISSUE TITLE
MinimigAga 1.2 Core: OSD off-screen on HighRes non interlaced modes 

### ISSUE THREAD

**Issue by AmigaIstMiST** [mist-devel/mist-binaries#5] opened 2016-03-19 08:09 UTC
Hi everyone, this is my first post on this board. I am not a HW Developer, only a user, but I think it might be helpful to post the issues I have found.

Testet with MinimAGA core 1.2 (affects earlier versions, too)
Using NTSC mode:
1. LowRes (640x200): OSD is centered (OK)
2. HighRes (640x400) interlaced: OSD is centered (OK)
3. HighRes (640x400 ECS/ AGA) non-interlaced : OSD is only partly visible on the rigth side of the display and not usable, it's for example not possible to change disk images.

**Comment by harbaum** [comment] 2016-03-19 08:29
Thanks for reporting this. Now that the amiga core got adjustable video modes the osd needs to be able to adopt to this. Many other cores already have this feature. I'll see if I can port one of these back to the amiga core.

**Comment by sorgelig** [comment] 2016-03-21 01:31
How to enable 640x400 non-interlaced mode? 
I don't see this in WB 3.1.

**Comment by AmigaIstMiST** [comment] 2016-03-21 06:24
You need to pull the "double ntsc" monitor type from the "storage" to the "devs" folder. After this, reboot first.

**Comment by SpeedD408** [comment] 2016-03-21 20:58
I can confirm.  When in DoubleNTSC everything is shifted down and the the
right about 2 inches on my screen.

**Comment by harbaum** [comment] 2016-03-21 21:32
As I said: I know the reason and will fix it asap.

**Comment by SpeedD408** [comment] 2016-03-21 21:49
Great.  Thank you.  I just didn't see that it was confirmed by anyone else,
so I thought I would confirm it.  Sorry for the noise.

**Comment by harbaum** [comment] 2016-03-22 20:47
No problem. I was just trying to say that you don't need to prove that the bug really exists.

**Comment by harbaum** [comment] 2016-06-02 20:02
I just submitted a fix for this for inclusion into the next release.

**Closed by harbaum** 2016-06-02 20:02 UTC
