### ISSUE TITLE
[Amstrad CPC] core

### ISSUE THREAD

**Issue by juri74** [mist-devel/mist-binaries#35] opened 2016-12-18 13:42 UTC
not an issue but just a request:
could be possible to "unlock" 15khz RGBS mode please?
thanks

**Comment by renaudhelias** [comment] 2016-12-18 17:20
Amstrad is using a 50Hz display, not interlaced. It cannot be scandoubler for mode 2 (lost of precision)

Using mist.ini scandoubler parameter, you can enable original signal output (SCART), but it was a blind development : some signal are ouput, but VSYNC/HSYNC offset are not confirmed.

I tested with my TV, but no way to run any 15kHz signals on it correctly (SNES doesn't run on it, same problem of display moving up), so I'm blind here. I have to validate a TV before validating my code...

Process generating TV signals is "aZRaEL_process" in
https://github.com/renaudhelias/CoreAmstrad/blob/master/BuildYourOwnZ80Computer/simple_GateArrayInterrupt.vhd
RED_out,GREEN_out, BLUE_out, HSYNC_out, VSYNC_out.

**Comment by juri74** [comment] 2016-12-20 14:12
sorry for late reply,
i noticed other cores uses a RGBS (RGB + COMPOSITE sync) for 15khz video signal, maybe the problem is that HV sync control..
unfortunately VHD is alien language for me :(

**Comment by harbaum** [comment] 2016-12-20 19:37
SCART TVs expect a composite sync. The VGAs vsync is connected the SCART pin used to detect a RGB signal and is constantly driven high. A TV will not cope with a video signal with separate H and V sync.

Bu tit's usually sufficient to xor hsync and vsync to get a csync acceptable for many TVs.

**Comment by juri74** [comment] 2016-12-21 08:42
> But it's usually sufficient to xor hsync and vsync to get a csync acceptable for many 
> TVs.

@renaudhelias maybe could you give it a try?
thanks

**Comment by renaudhelias** [comment] 2017-01-27 11:52
Added to TODO-list
(TODO-list is here : http://www.cpcwiki.eu/index.php/FPGAmstrad#Effort_done)

**Comment by renaudhelias** [comment] 2017-01-27 15:45
http://github.com/mist-devel/mist-board/tree/master/tutorials/soc#lesson-11-15khz-tv-video could be fine to adapt first (50Hz/60Hz), as it I could begin by... validating my TV.

**Comment by renaudhelias** [comment] 2017-01-27 19:13
@harbaum can you align lesson11 60Hz 15kHz with unix "modeline" command protocol ? (refactor) / "modeline" is an unix command showing all world screen/tv parameters for generating easily all world screen/tv signals...

**Comment by harbaum** [comment] 2017-01-27 21:36
@renaudhelias thanks for the hint. I'll have a look.

**Comment by renaudhelias** [comment] 2017-03-08 18:14
I saw in tutorial the use of xor for TV output, so then I try it at home, my TV sucks @15kHz.

So I put a try by here : https://github.com/mist-devel/mist-binaries/tree/master/cores/amstrad/experimental

@juri74 perhaps you can try this not-tested version.

**Comment by squidgydude** [comment] 2017-03-10 10:02
renaudhelias, if you point me to your source code changes for these 15khz tests I can have a look. I've done quite a lot of 15khz work recently and can test it properly.

**Comment by renaudhelias** [comment] 2017-03-10 10:18
Amstrad is 50Hz

Candidate patchs are here (one is inversing the output signal...) :
- http://github.com/mist-devel/mist-binaries/blob/master/cores/amstrad/experimental/amstrad_170308_r005.8.14e_xorTV.txt
- http://github.com/mist-devel/mist-binaries/blob/master/cores/amstrad/experimental/amstrad_170308_r005.8.14e_xor2TV.txt
Perhaps one between amstrad_170308_r005.8.14e_xorTV.rbf and amstrad_170308_r005.8.14e_xor2TV.rbf is running fine.

Component concerned is :
http://github.com/renaudhelias/CoreAmstrad/blob/master/BuildYourOwnZ80Computer/MiST_SCART.vhd
This MiST_SCART.vhd component does use the mist.ini feature http://github.com/mist-devel/mist-binaries/blob/master/cores/amstrad/experimental/mist.ini scandoubler_disable=1

Another component can be patched also :
http://github.com/renaudhelias/CoreAmstrad/blob/master/BuildYourOwnZ80Computer/simple_GateArrayInterrupt.vhd
My second patch is not a great one (xorTV2 and xor2TV2 alternative), I did just try hacking the "HSYNC_out" output (used for TV signal) by here
In this last component simple_GateArrayInterrupt.vhd you'll find the TV signal output generation :
- RED_out : out  STD_LOGIC_VECTOR (5 downto 0);
- GREEN_out : out  STD_LOGIC_VECTOR (5 downto 0);
- BLUE_out : out  STD_LOGIC_VECTOR (5 downto 0);
- HSYNC_out : out STD_logic;
- VSYNC_out : out STD_logic

**Comment by renaudhelias** [comment] 2017-03-10 10:37
If you never tryed CoreAmstrad all is explain here http://github.com/mist-devel/mist-board/wiki/CoreDocAmstrad#installation (you can contact me also : renaudhelias at gmail dot com)

**Comment by squidgydude** [comment] 2017-03-10 10:53
Having a quick look [this one](https://github.com/mist-devel/mist-binaries/blob/master/cores/amstrad/experimental/amstrad_170308_r005.8.14e_xorTV.txt) looks correct to create the csync. I can't check properly until I get home and test the cores and see what signals are being generated.

See my quick conversion changes of TCA2600 [here](https://github.com/wsoltys/TCA2601/commit/c04d3afc82e629f4bd4bbcca1ebb20e31f71d976#diff-7db66cac63872739ce0c098614ab0bba). Specifically:
VGA_HS <= not (vga_hsync_i xor vga_vsync_i) when tv15khz='1' else vga_hsync_i;
VGA_VS <= '1' when tv15khz='1' else vga_vsync_i;

**Comment by juri74** [comment] 2017-03-10 12:12
hello @renaudhelias ,

my wife is at the hospital i do not have time to try at the moment sorry :(
i will publish your test link on my fb page and let other mist users to try it out.
thanks for your effort!!

**Comment by renaudhelias** [comment] 2017-03-22 21:31
amstrad_170308_r005.8.14e_xorTV will be integrated in next realise.
DrOG from atari-forum succeeded in running with it. I think last problem is about VSYNC/HSYNC signal length.
![471amstrad_170308_r005 8](https://cloud.githubusercontent.com/assets/13655988/24221612/492cb16e-0f4f-11e7-9b81-1c814059fd75.png)

**Comment by juri74** [comment] 2017-03-23 13:59
great!

**Comment by renaudhelias** [comment] 2017-03-23 17:45
amstrad_170323_r005.8.15c12.rbf published (for ones of atari-forum), normally does resolve OSD in TV mode. It's candidate 12 because I'm currently working on next version (FDC)

**Comment by KLNHOMEALONE** [comment] 2017-03-28 16:27
Please add AMX mouse support if possible

**Comment by renaudhelias** [comment] 2017-03-28 17:23
amstrad_170328_r005.8.15c16e.rbf published "applying Gerald HSYNC/VSYNC width formula"

**Comment by renaudhelias** [comment] 2017-03-28 17:26
@KLNHOMEALONE added to TODO-list (http://www.cpcwiki.eu/index.php/FPGAmstrad)

**Comment by renaudhelias** [comment] 2017-03-31 17:26
"Perfect and well-centered!" - DrOG
![ok](https://cloud.githubusercontent.com/assets/13655988/24561659/e708d1ca-1647-11e7-9f79-f865bacf58c2.png)

**Comment by renaudhelias** [comment] 2017-04-16 16:06
I've got a TV !
PAL 50Hz 15KHz Parrot test ( https://github.com/mist-devel/mist-board/blob/master/tutorials/soc/lesson11/lesson11.png ) does pass on it, but CoreAmstrad doesn't.
I'll refactor Parrot test into modeline and then in a second step will try to adapt it to CoreAmstrad output :)

**Comment by renaudhelias** [comment] 2017-05-07 10:48
I compare HSYNC/VSYNC width with Parrot test, it results this experimental version : cores/amstrad/amstrad_170507_r005.8.14.2e.rbf (not tested)

**Comment by renaudhelias** [comment] 2017-05-07 16:55
Ok, back from Tetalab laboratory.
![tvoutputok](https://cloud.githubusercontent.com/assets/13655988/25783067/1b2da996-3356-11e7-982a-865c584ad982.png)
r005.8.14.2e.rbf does run fine, one char or one half-char h-offset in left (screen not horizontally centered)
![tvoutput_strangehalfcharhdisp](https://cloud.githubusercontent.com/assets/13655988/25783065/1b251dda-3356-11e7-834d-b009916e4058.png)
All chars are displayed, but HDISP does come too early and go away too later : about one half-char each.
![tvoutputhvbordersize4](https://cloud.githubusercontent.com/assets/13655988/25783066/1b25dbb2-3356-11e7-857e-845f15e4da22.png)
Ignoring the two previous bugs. Border seems having a 4 chars size (H and V)

**Comment by renaudhelias** [comment] 2017-05-08 17:24
amstrad_170507_r005.8.14.2j.rbf TV mode with borders (not tested)

**Comment by renaudhelias** [comment] 2017-05-10 22:36
r005.8.14.2j OK for me, just an half-char offset of HDISP (cutting chars at right) but border limits OK.
Tryed also with another TV (same model but image not stable verticaly (blurred screen))
![r005 8 14 2j-boot](https://cloud.githubusercontent.com/assets/13655988/25924166/99237078-35e1-11e7-9de2-9c348ebcbc97.png)
![mamouth](https://cloud.githubusercontent.com/assets/13655988/25924199/cef3ae70-35e1-11e7-9b40-c320d04a05a3.png)

**Comment by renaudhelias** [comment] 2017-05-11 17:02
r005.8.14.2k , HDISP correction, not tested.

**Comment by renaudhelias** [comment] 2017-05-13 20:36
r005.8.14.2 realized

**Closed** 2017-06-04 13:08 UTC
